ThatConference/that-website

components/Footer/PageFooter.js
components/Footer/index.js
components/Header/index.js
components/shared/Icon.js
components/shared/SocialLinks.js

fill in detail to footer

---

components/HomePage/Hero.js
components/Meta.js
styles/baseTheme.js
styles/globalStyle.js

and header font and global copy styles

---

components/HomePage/LearnMore.js
pages/index.js

add learn more section to homepage

---

components/HomePage/Hero.js
components/HomePage/SpeakerHighlight.js
components/shared/Icon.js
components/shared/ProfileItem.js
components/shared/RoundImage.js
pages/index.js
styles/globalStyle.js

add homepage speaker highlight block

---

components/HomePage/MeetCampers.js
components/HomePage/SpeakerHighlight.js
components/shared/ContentSection.js
components/shared/ProfileItem.js
components/shared/RoundImage.js
pages/index.js

add meet campers section

---

components/Nav/index.js

Noticed typo in top navigation bar - changed "Play Your Trip" to "Plan Your Trip".

Updated text on Plan Your Trip

---

lib/sentry.js
next.config.js
now.json
package-lock.json
package.json
pages/_app.js
pages/_error.js

update your env to include `SENTRY_DSN`

enables sentry and adds a base custom error page

---

components/Header/MessageBar.js

Updated copy on call for speakers header bar message

---

next.config.js

it doesn't seem to work as expected.

removing useFileSystemPublicRoutes usage

---

components/HomePage/MeetCampers.js

Added Erin Gemoll to Crew. Carrie's last name case changed.

---

pages/workinprogress.js

Added Work in Progress landing page

---

components/Footer/PageFooter.js
components/Footer/index.js
components/Header/index.js
components/HomePage/SponsorHighlight.js
components/shared/LinkButton.js
components/shared/SocialLinks.js
pages/index.js

- fix broken link button 
- clean up footer

Add sponsors to home page

---

pages/_error.js
pages/wi/become-a-partner.js
pages/wi/index.js
pages/work-in-progress.js
public/robots.txt

Started adding some minor seo information.
tip - make sure you use the `key` attribute when you want to overwrite a element in the head.
https://nextjs.org/docs#populating-head

adding some seo meta

---

components/shared/Redirect.js
lib/initApollo.js
lib/redirect.js
next.config.js
package-lock.json
package.json
pages/wi/prospectus.js

adds a dedicated page to the WI event to point at the prospectus. Down the road it should call to the event meta data to get the url but for now we will just hardcode it.
* refactors redirect for broader us.
* refactored the redirect component.

enables a page to redirect to the WI prospectus

---

README.md

Not final but trying to get items added we can start to iterate and build off of.

add the beginnings of contribution guide to readme

---

components/HomePage/Testimonials.js
utilities/breakpoint.js

Make testimonials flow responsively on mobile, Fixes #82

---

components/shared/Icon.js

This was filling the terminal with `undefined` logs.

Quiets a loud console log

---

markdown/blog/that-2019-holiday-buying-guide.md
pages/blog/[post].js

and adds picture this clothing to list

move blog to root

---

pages/_document.js
pages/wi/index.js

Brings back in Active Campaign to the website.
* enables the newsletter signup on only the index page.
* enables ac tracking.

enables ac tracking and email signup modal

---

components/shared/NewsletterSignupForm.js
pages/wi/index.js

update so that it recognizes the button as the submit

fix newsletter signup

---

components/BlogList/BlogListItem.js
components/Footer/MobileFooter.js
components/Header/Nav.js
components/Header/NavItem.js
components/Header/index.js
components/HomePage/Hero.js
components/shared/LinkButton.js
markdown/blog/2019-cs-ed-week.md
markdown/blog/that-2019-holiday-buying-guide.md
pages/blog.js
pages/wi/become-a-partner.js
pages/wi/contact.js
pages/wi/partners.js
pages/wi/plan-your-trip.js
styles/baseTheme.js
styles/globalStyle.js

Adds:
- top nav
- contact us page
- plan your trip page
- blog listing page

Build out ancillary pages and nav

---

pages/wi/partners.js

Used the term `partner` more consistent

reword opening paragraph with

---

.vscode/settings.json
components/Header/index.js
pages/_app.js
pages/wi/[markdown].js
pages/wi/call-for-counselors.js
pages/wi/index.js
pages/wi/partner/[slug].js
pages/wi/partners.js
pages/wi/plan-your-trip.js

puts the apollo client back at the _app rather than at each page.

moves apollo client to _app

---

.env.build.sample
.env.sample
.vscode/settings.json
lib/auth0.js
lib/initApollo.js
lib/withApolloClient.js
next.config.js
now.json
package-lock.json
package.json
pages/api/callback.js
pages/api/login.js
pages/api/logout.js
pages/api/me.js

Enables:
* will now retrieve the proper token to authenticate against the api.
* saves token between sessions.
* updates apollo client to correctly add the http headers when necessary.
* removes the activity bar coloring.

enables oauth for api calls

---

components/CallForCounselors/Header.js
components/CallForCounselors/Perks.js
components/CallForCounselors/Process.js
components/CallForCounselors/SummerCamp.js
components/CounselorSelectionProcess/Header.js
components/CounselorSelectionProcess/TheProcess.js
components/Header/MessageBar.js
components/Header/NavItem.js
components/HomePage/Hero.js
components/shared/ContentSection.js
pages/wi/call-for-counselors.js
pages/wi/counselor-selection-process.js
styles/globalStyle.js

Includes 💅 to match adjustments made across rest of site.
Start to get the call for counselors landing pages linked up into the site without opening up to the public yet. Comments out portions of pages that link into call for counselors flow.

link up call for counselors and open to main site

---

public/.well-known/microsoft-identity-association.json

remove new folder for domain validation

---

README.md

Updates instruction to new requirement, per #118

Updates env file setup instruction

---

components/CallForCounselors/Header.js

Edited copy for consistency with the rest of the page.

---

components/CounselorAgreement/Acknowledgment.js
components/Member/Profile/ContactInfo.js
components/Page.js
pages/_app.js
pages/member/create.js
pages/wi/counselor-agreement.js
pages/wi/session/submit/details.js
pages/wi/session/submit/index.js

Adding redux back in to store user to avoid the weirdness happening on the branch now. Seems like something with server vs. client rendering, not sure... and still no luck with apollo local state. In interest of time bringing this back so we can keep moving.

add user store back to redux

---

components/Member/MySessions/Current.js
components/Member/SessionEdit/Details.js
components/Session/Submit/Preview.js
hooks/requireAuth.js
pages/member/create.js
pages/member/edit.js
pages/member/session-edit/[sessionId].js
pages/wi/counselor-agreement.js
pages/wi/session/create.js
utilities/validation.js

Add scroll to top to Router.Push() calls

---

components/CallForCounselors/Process.js
pages/member/my-sessions.js

Made changes to the following files to correct issues noted in subject:
/member/my-sessions.js - removed text regarding 3 session limit
/call-for-counselors/Process.js - updated capitalization on “More About The Counselor Selection Process” button

Corrects issues #294 and #290:

---

components/Header/MemberNav.js
components/Member/Profile/Image.js
components/Member/SessionEdit/Details.js
components/Session/Submit/AdditionalInfo.js
components/Session/Submit/Details.js
components/Session/Submit/Intro.js
components/Session/Submit/Lastly.js
components/shared/FormLayout.js
components/shared/LinksInput.js
components/shared/LoadingIndicator.js
components/shared/SquareButton.js
components/shared/StringsInput.js
pages/member/create.js
pages/member/edit.js
pages/member/my-sessions.js
pages/member/session-edit/[sessionId].js
utilities/constants.js

includes marking session fields required and adjusts + and - icon buttons

Better loader

---

components/CallForCounselors/Header.js
components/Header/MessageBar.js
components/Member/Profile/OnlinePresence.js
package-lock.json
package.json

also fixes husky pre-push hook

update banner message. Add that slack link to label

---

components/HomePage/Hero.js
components/shared/SocialLinks.js
utilities/constants.js

add github to social links

---

components/Header/index.js
components/Member/MySessions/Current.js
components/shared/NavItem.js
components/shared/YouTubeVideo.js
pages/blog/[post].js
pages/member/my-sessions.js
pages/wi/tickets.js

not complete review, but got some items standing out... time to go show @csell5 how things are done

adjust mobile styling to not be so uck

---

components/HomePage/SponsorHighlight.js
components/Session/Submit/Intro.js
next.config.js
now.json
pages/wi/[markdown].js
pages/wi/call-for-counselors.js
pages/wi/index.js
pages/wi/partners.js
pages/wi/plan-your-trip.js

sort partners on listing page
refactor for latest partner api update
fixes #337

move event id into env var. 

---

components/Member/MySessions/Current.js
pages/wi/index.js
utilities/constants.js

Remove staff from WI home page
other half of change for session status DECLINED in https://github.com/ThatConference/that-api-sessions/pull/40

Update session status to NOT_ACCEPTED from DECLINED. 

---

components/HomePage/SpeakerHighlight.js
markdown/attendee-handbook.md
markdown/blog/WI-2020-call-for-counselors-open.md
markdown/code-of-conduct.md
markdown/commitment-to-diversity.md
markdown/counselor-handbook.md
markdown/counselor-submission-faq.md
markdown/family-handbook.md
pages/wi/call-for-counselors.js
pages/wi/speakers.js

Updated copy on various pages to change references of "Speaker" to "Counselor" for consistency. 
Also updated copy on the following items:
Code of Conduct
Commitment to Diversity
Counselor Handbook
Family Handbook
Attendee Handbook

Copy updates to change "Speaker" to "Counselor" throughout site (and other items noted below)

---

now.json

Sets deploy regions to US GCP data centers only

Add specific deploy regions for Zeit

---

components/Page.js
components/Session/Voting/Review/Content.js
components/Session/Voting/Review/Header.js
components/Session/Voting/Shared/Thumbs.js
components/Session/Voting/Vote/Content.js
components/Session/Voting/Vote/Header.js
package-lock.json
pages/_app.js

* creates global hotkeys for the page
* removes ^^ from app.
* fixes react key issues
* cleans up unnecessary elements

hotkey and other cleanup

---

components/Header/MessageBar.js

Remove secondary color from Messages area so the entire header is 1 color.

Standardize Header Color

---

components/Member/Profile/Bio.js
components/Member/Profile/Image.js
components/Session/Voting/Shared/SessionContent.js
styles/globalStyle.js
utilities/constants.js

- allows for simplified profile (only requires bio and image when `canFeature` is truthy)
- fix for organizer notes to be saved on key press (fixes #405)
- adds key for console warning on vote page (fixes #406)
- remove global input with

Bug fixes for voting

---

.env.build.sample
components/Page.js
lib/initApollo.js
lib/sentry.js
lib/withApolloClient.js
next.config.js
now.json
package-lock.json
package.json
pages/_app.js
pages/_error.js

* Adds log rocket
* replaces error page
* logs sentry errors from error page
* adds correlationid to the api calls
* adds more user context to errors

errors, errors, moar errors

---

components/Session/Voting/Shared/SlimSession.js
components/Session/Voting/Shared/VotingFooter.js
components/shared/SavingOverlay.js
pages/wi/voting/vote.js

also updated "Organizer Notes" to "Organizer Feedback"

set tree color when key pressed

---

components/Footer/index.js
components/Header/Nav.js
components/HomePage/Timeline.js

- set mobile header nav menu font to blu on partner profile page
- stack milestone items on timeline with same date
- stack footer on mobile for readability

Site adjustments

---

pages/wi/voting.js

Updating voting instructions to include info on 'Organizer Feedback' textbox

---

.env.sample
README.md

Resolves #429 
Update `.env.sample` file to include missing keys.
Update ReadMe to state if previously setup environment, verify all keys are present in their files.

update env.sample file and readme

---

components/Session/Voting/Shared/SlimSession.js

Ensures session review thumb icons are not too small to use

---

components/Member/Profile/Image.js

If you just want to go the route of filtering on the main 3 image types, this should do the trick.

Member Image Filtering on Types for Issue #421

---

components/Member/MySessions/Current.js
pages/member/my-sessions.js

Copy updates to My Sessions page / Also removes ability to create new sessions from this page as community voting is now open.
Fixes #431.

Copy updates to My Sessions page / Remove ability to create new sessions

---

components/HomePage/Timeline.js

Solved the Home Page Timeline issue

---

components/PartnerDetail/HeroSection.js

Set to cover on center for background image.

Changed Hero Background Styling

---

pages/partner/[slug]/job/[jobSlug].js

Bug Fix: 'Remote' indication on job listing detail page

---

markdown/blog/april-2020-update.md

Made various typo corrections in the April 2020 update.

---

components/Footer/PageFooter.js
components/Header/root.js
components/RootHomePage/Community.js
components/RootHomePage/Events.js
components/RootHomePage/Keynotes.js
components/RootHomePage/LiveStream.js
components/RootHomePage/Shop.js
components/RootHomePage/SignUp.js
components/RootHomePage/StayInTouch.js
utilities/constants.js

- addressed issues found during QA
- fixed a few mobile styling issues including the horizontal scroll.

addressed noted issues

---

components/Member/Profile/ContactInfo.js

Updates site to work with new graphql Slug scalar.
Add failed slug check when graph error returned

Update member slug for new api slug scalar

---

CONTRIBUTING.MD
markdown/blog/refactoring-THAT-conference-2020.md

Added excerpt to latest blog post and added excerpt requirement to contributor.md for future reference.

Add blog post excerpt to post and contributors

---

components/Member/Profile/ContactInfo.js

Added conditional for ui slug validation

---

components/Footer/index.js
components/Header/Nav.js
components/Header/default.js
components/OneDay/Partners.js
components/OneDay/Tickets.js
components/RootHomePage/Events.js
components/shared/DetailToLearnMore.js
components/shared/TopPartners.js
now.json

- update nav routing/linking in header and footer
- pointer on partner logo hover
- fix up blog link on root landing

Fixes from testing 

---

pages/wi/2020/index.js

Initial ticket copy for WI 2020 event

Ticket copy for WI 2020

---

pages/wi/2020/index.js

Changed `Patron` to `Camper Patron`

change patron ticket name

---

components/OneDay/Partners.js

On one-day page, Displays corporate partners first followed by partners

Sort partners by Corporate Partner first

---

components/Header/SecondaryMemberNav.js
components/Header/root.js

possible stop-gap until we get the full nav in the header so that user can get to profile and logout

add member nav to root layout

---

components/BlogList/BlogListItem.js

fixes #539 
Added a width of 22rem.  This can be changed to any other value as desired.

add width to blog list images

---

components/Member/MySessions/Current.js
components/Member/SessionEdit/Details.js
components/Session/Submit/AdditionalInfo.js
components/Session/Submit/Details.js
components/Session/Submit/Intro.js
components/Session/Submit/Lastly.js
components/shared/SessionPreview.js
utilities/constants.js

Updates website to work with graphql path change on create and update of sessions

Update api calls for sessions changes with that-sessions-api pr#65

---

components/Member/Profile/Bio.js

Rewording of public profile checkbox

---

markdown/blog/introducing-that-dot-us.md

everyone, every one, some grammar thing

newsletter small fixes

---

components/RootHomePage/Blog.js
components/RootHomePage/Keynotes.js

root page
update blog liisted
add keynote and panel to "past keynotes" section

update blog listed and add Keynote and panel to root page

---

components/RootHomePage/Events.js

didn't update website PR after changing parameter in api.

add changed parameter 'findBy'

---

components/EventHomePage/SponsorHighlight.js
components/EventPages/OneDayEvent.js
components/Header/default.js
pages/[markdown].js
pages/wi/2021/[markdown].js
pages/wi/2021/call-for-counselors.js
pages/wi/2021/important-dates.js
pages/wi/2021/index.js
pages/wi/2021/jobs.js
pages/wi/2021/partners.js
pages/wi/2021/plan-your-trip.js

Refactored existing graphql queries to properly support the new events structure and input.
fixes #598

Refactored event graphql query calls

---

components/CounselorStart/Header.js
components/Header/MemberNav.js
components/Header/MessageBar.js
components/Header/SecondaryMemberNav.js
components/Member/MySessions/Current.js
components/Member/SessionEdit/Details.js
components/OneDay/Partners.js
components/PartnerDetail/MainLogoSection.js
components/RootHomePage/Events.js
components/layouts/Default.js
components/layouts/Root.js
components/shared/LinksInput.js
components/shared/StringsInput.js
components/shared/Timeline.js
pages/member/create.js
pages/member/edit.js
pages/member/session-edit/[sessionId].js
pages/member/session-preview/[sessionId].js
pages/members.js
pages/partner/[slug].js
pages/partner/[slug]/jobs.js
pages/wi/2020/jobs.js
pages/wi/2021/counselor-agreement.js
pages/wi/2021/important-dates.js
pages/wi/2021/jobs.js
pages/wi/2021/session/create.js
pages/wi/2021/voting.js
pages/wi/2021/voting/review.js
pages/wi/2021/voting/vote.js

Instead of importing the entire lodash library when needed, only pull in the lodash functions used in that particular component via named exports to reduce bundle size. 
Fired up the app locally and clicked through all the pages I could access.

use named exports for lodash

---

components/layouts/Default.js
components/layouts/Root.js
pages/_app.js

Want to extend the life of our account on that.us for right now.. Will put back in later.

puts a pause on logrocket

---

pages/thatus/[year].js

Adds a route to redirect any request to `/thatus` to that.us

enables that.us redirection

---

components/shared/Redirect.js

fixes #616 - returning from getInitalProps

---

components/shared/Redirect.js

fixes #616 again - returning from getInitalProps

---

components/shared/WhatToExpect/WhatToExpect.js
components/shared/WhatToExpect/WhatToExpect.spec.js
components/shared/WhatToExpect/WhatToExpect.stories.js
package.json
pages/wi/2021/become-a-partner.js
pages/wi/2021/index.js

Refactor Component to its own folder.  Update imports for new location.
Add Spec file
Add Story file
Fixes #557 
Builds, runs locally, tests pass, and storybook works.

refactor WhatToExpect for Storybook

---

components/shared/Timeline.js
pages/wi/2021/important-dates.js
utilities/utilityFunctions.js

Updates the important dates page to render dates properly. 
Stying of page and timeline section further refined as part of this work. 
Fixes #546
Running app locally, testing through Chrome, Brave and Safari on multiple size windows.

fix up important dates page

---

components/CallForCounselors/Header.js
components/CounselorAgreement/Header.js
components/CounselorStart/Header.js
components/shared/Title/Title.js
components/shared/Title/Title.spec.js
components/shared/Title/Title.stories.js
pages/member/my-sessions.js
pages/wi/2021/voting.js

Refactor Component to its own folder. Update Imports for new location.
Add Spec file
Add Story file.
Fixes #623 
Builds, passes tests, runs locally and storybook works.

Refactor and Storybook for Title Component

---

.vscode/settings.json
components/Header/SecondaryMemberNav.js
components/Header/root.js
components/shared/NewsletterSignupForm.js

Change top level navigation to use new drop down.
Fixes #627 
Reviewed with @csell5 and is responsive
- [NA] I have updated the documentation if necessary
- [NA] I have updated the stories as necessary
- [NA] I have updated the specs necessary

Navigation Menu

---

markdown/blog/wi-2021-call-for-counselors.md

Forgot to add the new md page when updating the blog

add new page 🤦‍♂️
