components/Footer/index.js, components/HomePage/NewsletterSignup.js, components/shared/NewsletterSignupForm.js, styles/globalStyle.js
Changes included:
- ditches the embedded AC form so we can roll our own
- updates styles for both newsletter components to better stack on mobile
- fix text and styling for homepage newsletter signup section within page
- signup for newsletter now keeps you on page (no redirecting or going through AC)
Along with this change I updated the confirmation email from AC:
- to send from hello@that instead of sara@that
- updated format to include new logo and colors
- added social icons
Fixes #61
=> create custom AC newsletter signup form

components/HomePage/MeetCampers.js
Leaves enough space for the long names, now uses the styled-css-grid rather than custom flexbox. 
Only 1 commit, but depends on #89 so that's included at this time.
=> Get campers using grid and flowing properly

CONTRIBUTING.MD
Instead of repeating the details on markdown throughout the issues to create more pages to the site I wanted make it accessible to all through the contributing page. 
More to add here but a skeleton to start and will give the detail contributors will need to create the markdown pages.
=> add contributing with markdown detail

components/Meta.js
so that we can isolate analytics to just production
=> disable google analytics for non-prod

.env.sample, README.md, pages/samples/toggle-page.js, pages/wi/speakers.js, utilities/togglePage.js
Adds a HOC that we can use to wrap a page that will check to see if query param given matches value set in `.env` then page can be displayed; if not sends user to page not found.
Example - speakers page added is wrapped in `togglePage`. Set `FEATURE_KEYWORD` to say `baconisgreat`. Fire up the local environment. 
Go to: http://localhost:3000/wi/speakers?feature=baconisgreat and page will load. 
Go to: http://localhost:3000/wi/speakers?feature=baconisgood, page not found
Go to: http://localhost:3000/wi/speakers, page not found
We can use this to wrap any page in that we want to lock down while we develop out. 
Not full feature toggle ability but a start to get us to 1/1.
=> add simple feature/page toggle

lib/withApolloClient.js
added a window check before calling getSession to make sure we were in SSR mode.
fixes #175
=> only grabbing session when in ssr mode

components/shared/ContentSection.js
Instead of setting different (responsive) breakpoints to get the tree to be centered, I used a calculation of 50% the view-width minus 1/2 of the tree's width. 
`calc(50vw - 8.5rem)` 
This will give you true-center in all screen resolutions.
Fixes #138
=> Added a more resilient way to center the Trees within the Content

.eslintrc.json
Having escaped HTML entities in JS files makes reading copy harder to grok. Chatted about this with the team and am disabling the rule. If we break stuff because of it, we can turn it back on and be more selective on it.
=> Disable the eslint rule to warn on unescaped HTML entities

components/CallForCounselors/Perks.js, components/CallForCounselors/Process.js, components/CounselorAgreement/Acknowledgment.js, components/CounselorAgreement/WhatsProvided.js, components/CounselorStart/Header.js
Now that we have removed the eslint rule for HTML entities, I have updated the copy for several files so they are easier to read.
=> Removed HTML entities from the Call for Counselors area.

package.json, pages/api/callback.js, pages/api/login.js
Add `/api/login?redirect-url=<path> ` to login page to redirect back to that path after authentication. 
Only use a path value. Any redirects to a domain will result being redirected to `/`
=> add redirect option to login

components/Member/Profile/ContactInfo.js
Added help text below the Mobile Phone field on the Member Profile contact information screen.
'What would be helpful to see' from Issue #287 is satisfied with this addition.
=> Help text added below the Mobile Phone field on the Member Profile

components/Footer/index.js, components/Header/Nav.js, pages/about.js, pages/contact.js, pages/wi/plan-your-trip.js
- add tickets to top nav
- move contacts to root page
- wire up tickets link to plan your trip page
- add bottom nav (more to do here as we sire up speakers and schedule, but a start to get some at the bottom)
=> add bottom THAT nav for general items

pages/_error.js
Removed path from new site URL that was being appended to the old site URL. Will now just direct to main page of old site. I also updated copy throughout the page to no longer use the &APOS; HTML code.
Also, we are not returning with the correct response code, it is showing a 200 OK status instead of 404.
What do I need to modify to return the 404 response code?
These initial changes correct issue #55
=> 'Page Not Found' page updated to take users to main page of old site

components/HomePage/SponsorHighlight.js
.. instead of /wi/partner/[slug], which was resulting in a "Page Not Found" error being displayed.
This corrects #371.
=> Changed the href on the Featured Camp Partner logo to point to /partner/[slug]

components/Page.js
This also resolves issue noticed in FireFox where on these short content pages, footer was off the screen and forced a scroll.
Fixes #390
=> force footer to bottom of short content page

now.json
redirects requests to root /sessions, and /speakers to the old website. 
POC Examples:
https://nextdump.brettski.now.sh/sessions/session/14010
https://nextdump.brettski.now.sh/speakers/speaker/adrhart
=> Add redirects for past sessions and speakers

components/Footer/PageFooter.js, components/Header/MessageBar.js, components/Header/index.js, components/Page.js, components/shared/ContentSection.js, pages/wi/index.js
The original PR #433 while addressing #308 and #68 ended up causing #453 and possibly #454 
After talking with @csell5 about it, I tried to fix the Logo issue of #453.  In doing so, the problem was not repeatable in a dev build locally.  Clark attempted to get me setup to use the production build locally which caused a different issue with GraphQL.  He looked at his setup and was seeing the same thing.
So, further discussion led to this PR to rollback the original changes from PR #433.  This will fix the Logo issue, may fix the mobile footer issue, but will also re-introduce the Horizontal scrolling issues.  It was deemed that the horizontal scrolling was the lesser of two evils.
I will be adding a new Issue linking and addressing the appropriate items.
Sorry for the headache.
=> rollback for PR443.  Fixing Horizontal scroll broke logo

components/shared/ContentSection.js
Fixes #456 
After fixing horizontal scrolling it was noticed that iPhone Max was now not working.  Issue was on ContentSection media query.  Adjust widths was done on xsmall and changed to small.
=> fix media query size for content section to accommodate big phones

components/shared/JobListing.js
Fixes #449 - issue with Show More button always showing on a JobListing.
Checked scrollHeight vs. clientHeight for the ref to determine if any content has overflowed. Happy to make changes or updates to the fix.
=> Fixed Show More button on JobListing - fixes #449

utilities/constants.js
Simple update to use correct linkedin url in our social references
=> fixed linkedin link to public url

components/HomePage/Timeline.js
Milestones only grouped, not sorted. Api switch to milestone collections which surfaced this issue.
=> Add sorting to timeline milestones

pages/_app.js
resolves #488 
Using https://docs.logrocket.com/docs/development#using-logrocket-in-development as a guide.
=> Resolve 488 - Don't Initialize LogRocket for local dev

components/PartnerDetail/HeroSection.js, pages/partner/[slug].js
Fix #450 
This is a potential solution that didn't involve changing the headerType of the page.  Text was borrowed from elsewhere on the site.
1. Add hero image (default)
2. Company Name is "Not Yet a THAT Parter"
3. Connect with Us link -> Become a Partner page in same tab.  If real parnter, continue using new tab
4. Text underneath taken from Top of Become a Partner Page
=> Potential fix for 450 No Header on No Partner

components/shared/PartnerLogoWithInfo.js
fix linkin reference, fix social object structure for use with SocialLinks.js
LinkedIn not showing for any parter
No links working for parter.
Turns out object being created was in the wrong for for the component using it. Updated creation of object for partner page.
=> fix social object structure for use with SocialLinks.js

components/shared/JobListing.js, components/shared/StandardStyles.js, pages/partner/[slug]/job/[jobSlug].js, pages/wi/2021/jobs.js
Styling and format handling for partner jobs
Adjusted styling of partner jobs and updated the job slug to use a `<pre>` instead of `<p>` for description.
=> styling fixes and changed p to pre

pull_request_template.md
Removes the duplication in the PR template and cleans up some of the prompts.
Fixes (no corresponding issue)
To make the PR process more informative and work better with THAT Community members who are contributing. 
Next person to open a PR is the winner. 
n/a
=> clean up and remove duplication from PR template

pages/member/[memberSlug].js
Corrects issue where member social icons don't have associated URL. 
Test current site social links e.g. https://www.thatconference.com/member/yrodriguez, the links are not active as they component did not receive a proper object and was unable to get the URL. 
The SocialLinks component get's the url: 
```react
return (
<SocialLinksContainer className={className} rowOrColumn={flexDirection}>
{Object.keys(socialLinks).map(key => {
return (
<SocialBlock size={size} className="social-block" key={key}>
<StyledLink
href={socialLinks[key].url}
target="_blank"
rel="noreferrer noopener"
key={key}
onClick={() => clickTracking(key)}
size={size}
ariaLabel={key}
>
...
```
Fixes # n/a
Corrects object created for socials which changed when description where added to social types (I believe)
- [X ] Bug …
=> fix member social links

components/shared/StandardStyles.js, pages/partner/[slug].js
- Updated partners slug page to use `<pre>` instead of `<p>` for about us and short description so basic formatting is preserved.
- While ensuring there was a shared global pre style I noticed that the shared pre and paragraph styles where duplicated so I refactored to use a styled css to reduce redundancy.
Fixes #571 
I tested this by viewing the partner mentioned in the bug, /partner/do-it-best-corp as well as other partners I knew had data such as, /partner/navitus-health-solutions and /partner/NVISIA to ensure all looked good.
I also confirmed other views that use the shared pre style such as, /wi/2021/jobs, where not impacted negatively by this change.
- [N/A] I have updated the documentation if necessary
- [N/A] I have updated the stories as necessary
- [N/A] I have updated the …
=> fix(Issue-571): Updated partners slug page to use <pre> tags for about and short description.

components/RootHomePage/Events.js
Must be merged **AFTER** that-api-events update (thatconference/that-api-events#87)
This change updates graphql query used to get active events by community due to a breaking change in PR thatconference/that-api-events#87.
=> Update communities query for new graph path

pages/wi/2021/partners.js
regression from pr thatconference/that-api-events#100
Data path not updated causing `undefined` result for button path.
=> regression. missed data path from events schema update

components/PartnerDetail/MainLogoSection.js, components/shared/RoundImage.js, pages/member/[memberSlug].js, utilities/constants.js
Use the member placeholder image on the partner detail page for instances when the partner member does not yet have a profile image uploaded.
Also, moves the person placeholder image to constants. 
Fixes #581
Example partner that has a member without a profile image:
Running app locally checking "Do It Best Corp" who currently has member without a profile image.
=> add placeholder image constant; add to partner detail

components/Member/Profile/ContactInfo.js
Updating wording for `isOver13` flag
Fixes #569
**Note**: without access to authorize I am unable to test or view profile page locally. But the wording is less characters so I don't believe it should cause any issues.
=> update wording on isOver13 profile check

components/shared/StandardStyles.js, pages/partners.js, styles/globalStyle.js
Adds search box on partners bag that searches partners `companyName` for a match to search text entered. Then filters the partner list to only display matching partners.
Fixes #467 
Tested through running app locally within Brave, Chrome and Safari on varying sizes. Also, clicked through pages rendering a graphic in top section since I updated the styles for that graphic.
=> add search to partners page

components/shared/SocialLinks.js, pages/partner/[slug]/job/[jobSlug].js
Adds an "Apply Now" button to the job detail page when the job has an `applyNowLink` set for it.
Also, updating formatting of text to match other parter and job areas of site.
Fixes #584
Marked as new feature as this functionality was never part of original design, and therefore never a broken. Was simple not yet implemented. 
Tested through the existing jobs in dB, both with and without `applyNowLink` values.
=> add apply now link to job page when exists

lib/sentry.js
Corrects the error happening when an unknown route is used. The code was blowing up in `sentry.js` trying to access a property on a property which didn't exist. 
Though this fixes the hard error, the resulting error page isn't want we want and will still need to be corrected in the future. Preferably someone who knows a bit more about Next.js. This is being tracked in issue #610
=> fixes http 502 running in vercel on bad route
